zeit/now-builders

now-build-utils/file-fs-ref.js, now-build-utils/package.json
Limit for simultaneous file streams in FileFsRef.toStream
=> [build-utils] semaToPreventEMFILE for file-fs-ref.js

now-build-utils/fs/run-user-scripts.js
Partially addresses https://spectrum.chat/thread/eddb8741-0508-4934-9cee-0bbc51f930db
=> [build-utils] use npm install if package-lock.json is around

.circleci/config.yml
=> Install Go before building packages

package.json
=> Add lint-staged precommit hooks + prettier

.circleci/config.yml, .gitignore, jest.config.js, package.json, packages/now-build-utils/package.json, packages/now-go/package.json, packages/now-html-minifier/package.json, packages/now-lambda/package.json, packages/now-md/package.json, packages/now-mdx-deck/package.json, packages/now-next/index.js, packages/now-next/launcher.js, packages/now-next/package.json, packages/now-node-bridge/package.json, packages/now-node-server/package.json, packages/now-node/package.json, packages/now-optipng/package.json, packages/now-php/package.json, packages/now-python/package.json, packages/now-static-build/package.json, test/integration/now-next/index.test.js, test/integration/now-next/no-package-json-and-next-config/now.json, test/integration/now-next/no-package-json-and-next-config/pages/index.js, test/integration/now-next/standard/next.config.js, test/integration/now-next/standard/now.json, test/integration/now-next/standard/pages/index.js, test/lib/run-build-lambda.js
Fixes https://spectrum.chat/thread/5e7c14aa-752a-45c3-a744-89721ecf7ceb
=> @now/next - don’t run path matching for lambdas

packages/now-node-bridge/bridge.js
Account when encoding is not set and the body is plain
=> account a case with no encoding. fixes #5

.eslintrc, package.json, packages/now-build-utils/file-ref.js, packages/now-next/index.js, packages/now-node-bridge/bridge.js, packages/now-node/index.js, test/integration/now-node/index.test.js, tsconfig.json
Use Typescript without the compilation step, it type-checks based on JSDoc comments:
https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript
I've only added types to now-node/index.js to start.
=> Initial Typescript JSDoc integration

.circleci/config.yml, packages/now-build-utils/file-fs-ref.js, packages/now-build-utils/fs/download.js, packages/now-build-utils/fs/glob.js, packages/now-build-utils/fs/rename.js, packages/now-build-utils/lambda.js, packages/now-md/index.js, packages/now-mdx-deck/index.js, packages/now-node/index.js, packages/now-optipng/index.js, packages/now-python/download-and-install-pip.js, packages/now-static-build/index.js
Makes circleci build pass
Ran two commands:
```
yarn prettier --write --single-quote packages/**/*.js
```
```
yarn lint --fix
```
Added branch ignore for publish-stable
Fixed one typescript error
=> Make PR builds reliable again

packages/now-node-server/index.js, packages/now-node-server/test/fixtures/09-no-bundle/now.json, packages/now-node-server/test/fixtures/09-no-bundle/with-bundle/index.js, packages/now-node-server/test/fixtures/09-no-bundle/with-bundle/is-bundled.js, packages/now-node-server/test/fixtures/09-no-bundle/without-bundle/index.js, packages/now-node-server/test/fixtures/09-no-bundle/without-bundle/is-bundled.js, packages/now-node/index.js
An option for now.json `config` to disable bundling.
=> Node-server bundle=false

packages/now-mdx-deck/index.js
=> Provide a complete implementation for `@now/mdx-deck`'s analyze function

errors/now-next-legacy-mode.md, errors/now-next-no-serverless-pages-built.md, packages/now-next/index.js
This was not present before, giving users a 404 page.
=> Fix broken error link

README.md
This links directly to the builder docs
=> Add link to builder docs

packages/now-next/index.js, packages/now-next/package.json
The `fs-extra` dependency already promisifies everything.
=> Remove fs.promised dependency

test/lib/deployment/test-deployment.js
Add headers to the error when a probe fails
=> Add headers to error when a probe fails

packages/now-build-utils/fs/run-user-scripts.js
This is only an issue for `now dev`, but will also probably be relevant when we add support for arbitrary Node.js versions. Since `now-cli` is run from a `pkg` binary with Node v10, native addons through `node-gyp` end up being compiled for that Node.js version, instead of v8.10.0 which is the version the Lambda `nodejs8.10` runtime uses.
Should fix https://github.com/zeit/now-cli/issues/1974.
=> [now-build-utils] Set `npm_config_target` env var when installing npm deps

packages/now-next/index.js
This will allow `node_modules/.cache/terser-webpack-plugin/**` to be included in the cache.
=> Add Terser Cache to Now Cache

.circleci/config.yml, package.json, yarn.lock
I already add secret in `circleci`. So technically speaking, it should be able to get the test coverage report.
=> Add Codecov report

packages/now-node-server/index.js, packages/now-node/src/index.ts
=> [now-node] Bump ncc to 0.17.3

packages/now-python/test/fixtures/02-wsgi-pipenv/Pipfile, packages/now-python/test/fixtures/02-wsgi-pipenv/Pipfile.lock, packages/now-python/test/fixtures/03-env-vars/Pipfile, packages/now-python/test/fixtures/03-env-vars/Pipfile.lock, packages/now-python/test/fixtures/06-content-type/index.py, packages/now-python/test/fixtures/06-content-type/now.json
- update python version to 3.6 in tests
- add `content-type` test
=> [now/python] Update python tests

packages/now-python/download-and-install-pip.ts
=> Fix typo in Python builder

packages/now-node/test/fixtures/07-content-length/probe.js
This PR adjusts test3 of 07-content-length
=> now/node: fix 07-content-length

packages/now-node/src/index.ts, packages/now-node/test/fixtures/09-include-files/now.json, packages/now-node/test/fixtures/09-include-files/root.edge, packages/now-node/test/fixtures/09-include-files/root.js
Fixes #381 
Demo(public): https://now-node-fs.sophearak.now.sh/
=> [@now/node] Make sure `includeFiles` have proper path inside lambda

packages/now-build-utils/src/types.ts, packages/now-next/package.json, packages/now-next/src/index.ts, packages/now-next/src/utils.ts, yarn.lock
This is for making `@now/next` invoke `next dev` directly.
=> Made `now-next` invoke `next dev`

packages/now-node/src/index.ts
This is a less complete version of #400, since it's still a WIP.
But this will enable lazy-building and act as a starting point for #400 to be rebased on top of once this is merged.
=> [now-node] Add initial Builder v2 API

packages/now-node/src/index.ts
Reverting #424 since this is failing tests. I want to be able to publish the builders in the morning and this is going to block unless we revert.
=> Revert "[now-node] Add initial Builder v2 API"

packages/now-go/index.ts
This will make `@now/go` rebuilt faster for `now dev` 🚀 
**How**
I actually not using the way like we do in `@now/next`. So instead I just using same workPath for `now dev` instead, and caching `go.mod` and `go.sum`.
I published `@now/go@dev`, so you can try it out.
=> [now-go] Improve rebuilt speed for `now dev`

packages/now-node-server/package.json, packages/now-node/package.json, yarn.lock
Bumps `@zeit/ncc` to the latest version
=> [node-node] Bump ncc to 0.18.2

packages/now-go/index.ts, packages/now-go/test/fixtures/08-include-files/index.go, packages/now-go/test/fixtures/08-include-files/now.json, packages/now-go/test/fixtures/08-include-files/templates/foo.txt
closes https://github.com/zeit/now-builders/issues/332
not sure it's good, I never written TS before ☺️
=> [now-go] Add support for `config.includeFiles`

packages/now-python/download-and-install-pip.ts, packages/now-python/index.ts
=> [now-python] Upgrade build env to python3.6

packages/now-go/go-helpers.ts
This PR have better checking for default installation of Go.
Previously we could only detect if users have a custom GOPATH.
=> [now-go] Improve go checking in user dev machine

packages/now-build-utils/src/file-ref.ts
This pull request removes dead code that was never documented and introduces a new scheme for ephemeral files.
=> [now-build-utils] Remove `mutable` option and add `sha+ephemeral` scheme

packages/now-next/src/dev-server.ts, packages/now-next/src/index.ts, packages/now-next/src/utils.ts
=> [now-next] Sync runtime env vars in dev server after `app.prepare()`

packages/now-go/go-helpers.ts
Show user descriptive error message when Go Modules not available.
=> [now-go] Give user descriptive error message when Go Modules not available

packages/now-python/index.ts
Make sure to keep `cwd` user clean, instead using `cwd/.now`.
=> [now-python] Make sure `cwd` user clean by using `cwd/.now`

packages/now-python/test/fixtures/09-url-params/now.json, packages/now-python/test/fixtures/10-url-params-http-handler/custom.py, packages/now-python/test/fixtures/10-url-params-http-handler/now.json
=> Add custom path and proper check

.github/CODEOWNERS
=> Update codeowners for python & rust

packages/now-next/src/index.ts, packages/now-next/test/integration/index.test.js
=> [now-next] Fix to deploy serverless error page 

README.md, test/lib/deployment/now-deploy.js
This will allow tests to run in Circle CI, even for PRs that are not ZEIT Members.
I also updated the README to mentioned that publishing was changed to GitHub Actions. Only the tests are run via Circle CI.
=> Enable tests for all

packages/now-python/now_init.py, packages/now-python/test/fixtures/01-cowsay/another/index.py, packages/now-python/test/fixtures/01-cowsay/now.json
Fixes #497
This PR improves the error message when the user is missing a `handler` or `app` variable.
=> [now-python] Improve error message

packages/now-next/src/index.ts, packages/now-next/src/utils.ts
Also adds util for making sure it is prepended correctly
=> Fix missing slash from prepending entryDirectory 

packages/now-next/src/index.ts, packages/now-next/src/utils.ts
=> Revert "Fix missing slash from prepending entryDirectory "

packages/now-next/package.json, packages/now-node-server/package.json, yarn.lock
=> Pin now-node-bridge dependencies in now-next and now-node-server

packages/now-node/src/index.ts
This bumps the layers to the latest canary version
=> [now-node] Bump layer versions

packages/now-python/test/fixtures/09-url-params/now.json, packages/now-ruby/tsconfig.json
Looks like a couple new files were not run through prettier/eslint.
Let's fix this so that we don't see these files changing on new PRs.
```
npx prettier --write ./**/*.js
npx prettier --write ./**/*.*.js
npx prettier --write ./**/*.ts
npx prettier --write ./**/*.*.ts
npx prettier --write ./**/*.md
npx prettier --write ./**/*.json
npx eslint . --fix
```
Follow up to #563
=> Run prettier

CONTRIBUTING.md, README.md
The guideline outlines the process to open a pull request on this repository and offers guidance on interpreting test errors.
I had a hard time understanding where to look for actual errors when working on #641 and #632. It wasn't until I saw https://github.com/zeit/ncc/issues/434 that I understood how I should have gone about investigating the errors I encountered. 
I tried to capture the essence of the interpretation process in the contributing.md file, hopefully this will make it easier for external contributors to contribute or at least provide more detailed and qualified feedback when they encounter errors.
=> Proposes a contributing guideline

packages/now-static-build/index.js, packages/now-static-build/package.json
=> [now-static-build] Use `cross-spawn` and npm for `now dev`

packages/now-python/src/index.ts, packages/now-python/test/fixtures/04-cowsay-pipfile/Pipfile, packages/now-python/test/fixtures/04-cowsay-pipfile/Pipfile.lock, packages/now-python/test/fixtures/04-cowsay-pipfile/index.py, packages/now-python/test/fixtures/04-cowsay-pipfile/now.json, packages/now-python/test/fixtures/05-cowsay-pipfile-local/local/Pipfile, packages/now-python/test/fixtures/05-cowsay-pipfile-local/local/Pipfile.lock, packages/now-python/test/fixtures/05-cowsay-pipfile-local/local/index.py, packages/now-python/test/fixtures/05-cowsay-pipfile-local/now.json
=> Support local Pipfile - fixes #567

packages/now-node/package.json, packages/now-node/src/helpers.ts, packages/now-node/src/types.ts, packages/now-node/test/helpers.test.js, yarn.lock
=> Revert "[now-node] Fix express not overriding helpers properties"

package.json
See docs here : https://github.com/lerna/lerna/tree/master/commands/version#--exact.
=> Add --exact to lerna version

packages/now-static-build/src/index.ts, packages/now-static-build/test/fixtures/11-cowsay-build/now.json, packages/now-static-build/test/fixtures/11-cowsay-build/package.json, packages/now-static-build/test/fixtures/11-cowsay-build/subdirectory/package.json
Use `build` and `dev` command if there is no `now-` version of the command for `@now/now-static-build`.
=> [now-static-build] Use `build` and `dev` command if there is no `now-` version

packages/now-build-utils/src/types.ts
Add `zeroConfig` to config type
=> [now-builds-util] Add `zeroConfig` to config type

packages/now-node-server/package.json
This difference between stable and canary should not exist.
=> Fixed package inconsistency

packages/now-python/now_init.py, packages/now-python/test/fixtures/12-asgi-function/index.py, packages/now-python/test/fixtures/12-asgi-function/now.json
=> [now-python] Support ASGI functions as well as classes

packages/now-build-utils/src/detect-builder.ts, packages/now-build-utils/src/detect-routes.ts
Fix default routes on windows and adjust error message for `@now/build-utils`.
=> [now-build-utils] Fix default routes on windows and adjust error message

.github/main.workflow
=> Add --pure-lockfile option

.github/main.workflow
Use `--pure-lockfile` on build
=> Use --pure-lockfile on build

packages/now-node/src/index.ts, packages/now-node/test/fixtures/04-tsx-resolve/dep.tsx, packages/now-node/test/fixtures/04-tsx-resolve/index.ts, packages/now-node/test/fixtures/04-tsx-resolve/now.json, packages/now-node/test/fixtures/04-tsx-resolve/tsconfig.json
This fixes and includes a for resolving .tsx files as described in https://github.com/zeit/node-file-trace/issues/10.
=> [now-node] Fix `.tsx` resolution

packages/now-go/index.ts
This PR improve support zero-config for `now dev`.
=> [now-go] Improve support for zero-config in now dev

packages/now-node-bridge/src/bridge.ts
=> [now-node-bridge] Increase timeout to 10 minutes

packages/now-build-utils/src/detect-builders.ts, packages/now-build-utils/test/test.js
=> [now-build-utils] Add nuxt builder detection

packages/now-static-build/src/index.ts
Improve error message for the output directory for zero config
=> [now-static-build] Improve error message for the output directory for zero config

packages/now-static-build/src/index.ts
Adjust error message for missing "public" dir
=> [now-static-build] Adjust error message for missing "public" dir

packages/now-build-utils/src/types.ts
=> [now-build-utils] Update Route type to support "status"

packages/now-build-utils/src/debug.ts, packages/now-build-utils/src/index.ts
This PR add `debug()` function for improve manage output from builders.
=> [now-build-utils] Add `debug()` function

packages/now-static-build/build.sh, packages/now-static-build/package.json
=> [now-static-build] Use ncc before publishing to npm

packages/now-build-utils/src/fs/run-user-scripts.ts, packages/now-static-build/src/index.ts
Reverts #864
This breaks `@now/next`
=> Revert "[now-build-utils][now-static-build] Fix spawn options for windows"

packages/now-ruby/build.sh, packages/now-ruby/package.json
=> [now-ruby] Use ncc before publishing to npm

packages/now-next/src/index.ts, packages/now-node/src/index.ts, packages/now-static-build/src/index.ts
=> [now-node][now-next][now-static-build] Enable node 10 for zero config

packages/now-static-build/src/frameworks.ts, packages/now-static-build/test/fixtures/12-create-react-app/now.json, packages/now-static-build/test/fixtures/12-create-react-app/public/testing-output-dir.txt
This will fix [this case](https://react-devtools-tutorial.now.sh/example-element-selector.js) (a CRA site with custom static files).
=> [now-static-build] Capture file system routes for CRA apps

.kodiak.toml
This will automerge PRs when the label is applied.
=> [tests] Add automerge

packages/now-routing-utils/src/index.ts, packages/now-routing-utils/test/index.spec.js
We recently added this feature to the proxy, it should be allowed to pass validation.
=> [now-routing-utils] Allow the combined use of continue and dest

packages/now-static-build/src/frameworks.ts, packages/now-static-build/test/fixtures/13-vue/now.json, packages/now-static-build/test/fixtures/13-vue/vue.config.js
=> [now-static-build] Fix zero config vue headers

CONTRIBUTING.md
This PR updates the contributing documentation to include instructions for deploying a Builder as a tarball.
Related to [this comment](https://github.com/zeit/now-builders/issues/914#issuecomment-521419865)
=> [docs] Add instructions for deploying Builder as a tarball

packages/now-static-build/src/frameworks.ts, packages/now-static-build/test/fixtures/25-saber/.gitignore, packages/now-static-build/test/fixtures/25-saber/README.md, packages/now-static-build/test/fixtures/25-saber/now.json, packages/now-static-build/test/fixtures/25-saber/package.json, packages/now-static-build/test/fixtures/25-saber/pages/_posts/my-example-post.md, packages/now-static-build/test/fixtures/25-saber/pages/_posts/super-long-article.md, packages/now-static-build/test/fixtures/25-saber/pages/_posts/super-short-article.md, packages/now-static-build/test/fixtures/25-saber/pages/about.md, packages/now-static-build/test/fixtures/25-saber/pages/index.md, packages/now-static-build/test/fixtures/25-saber/saber-config.yml, packages/now-static-build/test/fixtures/25-saber/saber-node.js
This PR adds [Saber](https://github.com/saberland/saber) to the optimized frameworks list, along with a test. The test fixture has been created with `yarn create site my-site`.
=> [now-static-build] Add Saber Optimization
