zeit/now-builders

now-next/index.js
Since we currently manipulate the package.json and `npm` will disregard it.
Fixes https://spectrum.chat/thread/517bce9b-06f0-48fc-9e98-23754fe36af2
Fixes https://spectrum.chat/thread/9b0a6966-74e2-4d70-8d24-f919eecd99c3
Most likely https://github.com/zeit/now-examples/issues/121 too
=> Don’t download package-lock.json in @now/next

packages/now-static-build/index.js
Adds an optional `distDir` config option to now-static-build.
To be used in `now.json` like
```json
{
"builds": [
{
"src": "package.json",
"use": "@now/static-build",
"config": { "distDir": "www" }
}
]
}
```
Closes #19
=> feat(now-static-build): add a `distDir` option

packages/now-next/index.js
Replaced the incorrect `environement` with `environment`
=> fix(Next): Fixed typo in environment

.circleci/config.yml
Attempting to fix this error:
```
> @now/cgi@0.0.13-canary.3 prepublish /home/circleci/repo/packages/now-cgi
> ./build.sh
main.go:14:2: cannot find package "github.com/aws/aws-lambda-go/events" in any of:
/usr/lib/go/src/pkg/github.com/aws/aws-lambda-go/events (from $GOROOT)
($GOPATH not set)
main.go:15:2: cannot find package "github.com/aws/aws-lambda-go/lambda" in any of:
/usr/lib/go/src/pkg/github.com/aws/aws-lambda-go/lambda (from $GOROOT)
($GOPATH not set)
```
=> [circle-ci] set `GOPATH` to ~/go

packages/now-php/launcher/launcher.go
1. The initial status code should be 200 (so that the first PHP call to `http_status_code` returns 200, as per the PHP documentation).
1. Extract the resulting status code and return it in the response.
=> [now-php] set the proper response status code

packages/now-go/main.go
This is in-line with the CGI and PHP (#83) builders.
(Side note: we really need to make a common go import for this logic…)
=> [now-go] always send the response as base64

packages/now-mdx-deck/index.js
Builds failing due to a breaking change in babel-plugin-styled-components 1.9.0. Updates mdx-deck to a version with babel-plugin-styled-components pinned to 1.8.0.
https://github.com/jxnblk/mdx-deck/issues/228
Related: https://github.com/styled-components/babel-plugin-styled-components/issues/182
=> Update mdx-deck dependancy

packages/now-bash/builder.sh, packages/now-bash/runtime.sh
This is more consistent with what you would expect for a lambda function, and we should maintain that convention.
For example: https://github.com/gkrizek/bash-lambda-layer
=> [now-bash] Rename `serve` function to `handler`

packages/now-node-server/index.js, packages/now-node/index.js
A more recent version of ncc is giving us better typescript support.
=> Bump `ncc` to v0.5.3

packages/now-php/test/fixtures/12-setcookie/probe.js, utils/go/bridge/bridge.go
this fixes several-values-per-header-name issue + test
=> Switch bridge.go response headers to map of slices

packages/now-next/utils.js, test/unit/now-next/utils.test.js
This makes sure larger applications don't run out of memory when building.
=> Increase heap size for @now/next

packages/now-bash/index.js
So that the build logs of the bash script are sent to the deployment logs.
=> [now-bash] add `stdio: inherit` to builder.sh script

packages/now-bash/runtime.sh
Also log the exit status of the `handler` function.
=> [now-bash] make the `curl` calls to AWS API silent

packages/now-next/utils.js, test/unit/now-next/utils.test.js
In preparation with a breaking change in the way Next.js builds, we need to lock the version used. (https://github.com/zeit/next.js/pull/5927)
=> Lock Next.js Version

packages/now-build-utils/package.json, packages/now-cgi/package.json, packages/now-go/package.json, packages/now-html-minifier/package.json, packages/now-lambda/package.json, packages/now-md/package.json, packages/now-mdx-deck/package.json, packages/now-next/package.json, packages/now-node-bridge/package.json, packages/now-node-server/package.json, packages/now-node/package.json, packages/now-optipng/package.json, packages/now-php-bridge/package.json, packages/now-php/package.json, packages/now-static-build/package.json, packages/now-wordpress/package.json
I noticed that the v2 logs show warnings about missing license. At first I thought it was my own code but then I realized it was the builders.
=> Add missing license to package.json

packages/now-bash/package.json, packages/now-build-utils/package.json, packages/now-cgi/package.json, packages/now-go/package.json, packages/now-html-minifier/package.json, packages/now-lambda/package.json, packages/now-md/package.json, packages/now-mdx-deck/package.json, packages/now-next/package.json, packages/now-node-bridge/package.json, packages/now-node-server/package.json, packages/now-node/package.json, packages/now-optipng/package.json, packages/now-php-bridge/package.json, packages/now-php/package.json, packages/now-python/package.json, packages/now-static-build/package.json, packages/now-wordpress/package.json
This will increase discoverability for users who see a builder, visit npmjs.com, and then want to know how to get to github to submit a PR.
The `repository` key will add a link to github from npm.
I also added the `directory` so the future npm will be able to link to the exact package in this monorepo. See [RFC 10](https://github.com/npm/rfcs/blob/latest/accepted/0010-monorepo-subdirectory-declaration.md) for more info.
=> Add repository key to package.json

packages/now-node-server/index.js, packages/now-node/index.js
This solves the warning seen in `/_logs` all the time:
```
warning package.json: No license field
```
=> Add license to satisify warning

packages/now-static-build/index.js, packages/now-static-build/test/fixtures/04-wrong-dist-dir/now.json, packages/now-static-build/test/fixtures/04-wrong-dist-dir/package.json, packages/now-static-build/test/fixtures/04-wrong-dist-dir/subdirectory/package.json, packages/now-static-build/test/test.js
When building an app with `now-static-build`, we check the existence of the distDir.
If there's no check like this, we are going to deploy a 404 page.
It's a user-error, but we need to mention it to the user.
=> Check for distDir existence inside `now-static-build`

packages/now-bash/runtime.sh
For `now dev` running on a MacOS machine, some of our builders will need
to be adjusted to be "platform-aware".
In this case, `mktemp` is provided by BSD instead of GNU, which doesn't
support the long form `--dry-run` flag, however both support the `-u`
flag which does the same thing.
=> [now-bash] Use `mktemp` dry run syntax that is compatible with BSD

packages/now-rust/src/request.rs, packages/now-rust/src/response.rs, packages/now-rust/src/strmap.rs
I was working on transitioning a now v1 docker rust project to now v2 and ran into a compilation error where Deserialize was included twice but considered ambiguous. This seems to be tied to using serde's `derive` feature over `serde_derive`, but AWS Lambda took the same approach.
Here's the project I eventually got deployed with my patch: [locale](https://github.com/mike-engel/locale) and the URL to view it: [locale.now.sh](https://locale.now.sh).
For more discussion: https://github.com/serde-rs/serde/issues/1441
=> @now/rust: Import Deserialize traits behind `de` and `ser` namespaces

packages/now-rust/src/body.rs, packages/now-rust/src/error.rs, packages/now-rust/src/lib.rs, packages/now-rust/src/request.rs
This changeset improves `@now/rust` to allow the for the following API:
```rust
pub fn handler(request: Request<()>) -> http::Result<Response<String>> {
let uri = request.uri();
let response = Response::builder()
.status(StatusCode::OK)
.body(format!(
"You made a request to the '/foo' lambda. URL: {}",
uri
))
.expect("failed to render response");
Ok(response)
}
```
This was originally suggested by @TooTallNate and @timothyis, and makes it so that the simplest API has no `Now_lambda` visible parts.
=> Allow simpler API for `@now/rust`

packages/now-rust/Cargo.lock, packages/now-rust/Cargo.toml
Already published at https://crates.io/crates/now_lambda/0.1.2
=> [now-rust] Publish 0.1.2 to crates.io

packages/now-build-utils/file-fs-ref.js
This helper function is very similar to the raw `FsFileRef` constructor, however it stats the file to retrieve the proper `mode`, so that settings like executable bits are not lost.
=> [now-build-utils] Add `FsFileRef.fromFile()` helper function

packages/now-node-server/index.js, packages/now-node/index.js
This fixes a regression introduced in ncc@0.13.2 and also prints the version of ncc used at build time.
See [release notes](https://github.com/zeit/ncc/releases/tag/0.15.1) for more info.
=> [now-node] bump ncc to 0.15.1

packages/now-node-server/index.js, packages/now-node/index.js
This has a couple fixes.
See release notes here https://github.com/zeit/ncc/releases/tag/0.15.2
=> [now-node] bump ncc to 0.15.2

packages/now-node-server/index.js, packages/now-node/index.js
This adds a {sourceMap:true} flag to ncc builds
=> [now-node] add sourceMap flag to ncc

packages/now-python/now_handler.py
What was originally a nice-to-have PR to only fix a few nitpicky [coding style](https://www.python.org/dev/peps/pep-0008/) issues with the amazing work done in https://github.com/zeit/now-builders/pull/99, turned out to be a PR to fix a real bug in the code - there is a missing import for `base64`.
I've used [pylama](https://github.com/klen/pylama) to lint the file, but I did not add it to the CircleCI config or anything as that would perhaps mean adding a whole new Python-oriented job and I'm not sure it's worth it at this stage.
=> [python] Add missing import, fix coding style

.circleci/config.yml, .circleci/publish.sh
Centralize the publishing logic for CircleCI to use.
There was a bug in the previous "Potentially publish stable release"
branch, such that it would be executed for non-tagged commits. The new
publish script checks if there are indeed any tags for the commit, and
bails if there are none.
As an additional bonus, there's now only one publish step in the CircleCI
config, because the publish script determines stable vs. canary based on
the tag name.
=> Add `publish.sh` script for CircleCI

packages/now-node-server/launcher.js, packages/now-node-server/package.json, yarn.lock
Update `@now/node-server` to use the latest `@now/node-bridge`, which removes the hard-coded port 3000 that was previously in-place, which was problematic for `now dev`. Now the `http.Server` instance listens on an ephemeral port which is detected by the Now node runtime.
=> [now-node-server] Update `@now/node-bridge` to v1.0.0-canary.2

packages/now-next/launcher.js, packages/now-next/legacy-launcher.js, packages/now-next/package.json, yarn.lock
Update `@now/next` to use the latest `@now/node-bridge`, which removes the hard-coded port 3000 that was previously in-place, which was problematic for `now dev`. Now the `http.Server` instance listens on an ephemeral port which is detected by the Now node runtime.
(Similar to 6101ba9d9505b0dacd6af49c1ee1e804313f9d17 and 8dc0c92c586d7d55e720d96359b8e2741845bb0f)
=> [now-next] Update `@now/node-bridge` to v1.0.0-canary.2

.prettierrc.json, package.json, packages/now-next/index.js, packages/now-next/package.json
This refactors two functions (extract method) and introduces a `prepareCache` export that saves the `node_modules/` directory (minus `.cache` & friends).
=> Cache Next.js `node_modules` for faster rebuilds

packages/now-build-utils/fs/get-writable-directory.js
`os.tmpdir()` abstracts away platform differences related to retrieving the writable temp directory, for example MacOS returns a user-specific temp directory instead of `/tmp`.
On AWS Lambda, [it returns `/tmp`](https://nexec-v2.n8.io/api/node?arg=-p&arg=require(%27os%27).tmpdir()).
More importantly, it removes the `__dirname/tmp` special-case when not running in prod. This was problematic for `now dev` because the module directory is not always writable (i.e. for a `pkg` binary).
=> [now-build-utils] Use `os.tmpdir()` for `getWritableDirectory()`

packages/now-next/index.js
This adds the ability for a build to emit `assets` that are required as part of the lambda deploy.
=> feat(@now/next): optional assets directory

packages/now-go/go-helpers.js
This might allow users to use `go.mod`, since on 1.12 they did the following:
> ... the go command now supports module-aware operations outside of a module directory, provided that those operations do not need to resolve import paths relative to the current directory or explicitly edit the go.mod file. ...
Perhaps after that, the users would be simply able to add this to their config files and make it work?
```
"build": {    
"env": {                                                              
"GO111MODULE": "on"    
}    
},
```
It's just an idea! But we would totally appreciate the update to 1.12 wether my previous reasoning is valid or not.
=> Can we update Go to 1.12?

packages/now-rust/index.js, packages/now-rust/src/request.rs
This supports a use case I have, where I need to have a couple extra things installed on the VM before the lambda is created (`wget`, `now`). This follows the same pattern that `@now/static-build` has.
For it to work, a `build.sh` file must be in the same directory as the entrypoint, which may be naïve, but I think works for most cases.
This also includes a fix for POST body parsing. For some reason, the way the Now event handles `encoding` is different than AWS Lambda's method, so it's usually `None` unless it's `base64` encoded. I don't think this should have any ill effects, but we'll have to wait for more users to use this ¯\\_(ツ)_/¯ 
Combined those two items into a single PR. If y'all want it split out into two, I'm happy to do that. Thanks!
=> [now-rust]: Allow a build.sh to be run prior to compile

packages/now-go/go-helpers.js, packages/now-go/index.js, packages/now-go/main__mod__.go, packages/now-go/package.json, packages/now-go/util/get-exported-function-name.go
This PR will be enabled `go.mod` support for `@now/go`.
**What changes?**
given go src file:
```golang
package function
import (
"fmt"
"net/http"
)
func Handler(w http.ResponseWriter, r *http.Request) {
fmt.Fprintf(w, "Hello from Go on Now 2.0!")
}
```
and `go.mod`
```
module my-function
require (
...
)
```
in the building process, go src file move into its desire folder, in this case `function`
and main go code for building handler would look like this
```golang
package main
import (
"net/http"
"my-function/function"
now "github.com/zeit/now-builders/utils/go/bridge"
)
func main() {
now.Start(http.HandlerFunc(function.Handler))
}
```
If go src file have `package main`, it will be using the previous flow.
=>  add support go.mod

packages/now-rust/index.js
This fixes an issue where `build.sh` was never detected due to how `entrypoint` works and my own naïvité.
=> [now-rust] Fix how build.sh is detected and run

packages/now-bash/index.js
This is important for `now dev`, where the `workPath` is re-used and thus leads to faster re-builds.
=> [now-bash] Use the `workPath` directory

packages/now-bash/runtime.sh
In situations where the handler responds very quickly, the `$event` file path gets deleted before the `_lambda_runtime_body` function can finish its work. So instead, just read that file once and cache it to a variable inside that function.
This is an attempt to fix this issue when the `handler` responds quickly:
```
/var/task/.import-cache/runtime.sh: line 78: /tmp/T/tmp.DShzjeah: No such file or directory
/var/task/.import-cache/runtime.sh: line 82: /tmp/T/tmp.DShzjeah: No such file or directory
```
=> [now-bash] Only read the `$event` body once

packages/now-next/index.js, packages/now-next/package.json, packages/now-next/utils.js, test/integration/now-next/index.test.js, test/integration/now-next/monorepo/www/static/test.txt, test/integration/now-next/static-files/next.config.js, test/integration/now-next/static-files/now.json, test/integration/now-next/static-files/package.json, test/integration/now-next/static-files/pages/index.js, test/integration/now-next/static-files/static/test.txt
This adds a test for uploading the static folder with `target: serverless` in a regular `@now/next` deploy and in a monorepo.
When being used in a monorepo there was a bug with outputting `static` files
=> Fix static files for latest now/next using target serverless

packages/now-node-server/index.js, packages/now-node/src/index.ts
This bumps `ncc` to version 0.16.0
=> [now-node] Bump ncc to 0.16.0

errors/now-next-no-serverless-pages-built.md
`now-builders` can't parse `next.config.js` because it can hold functions.
It expects `/.next` as the build output.
Closes: #288
=> Add note about @now/next not supporting distDir

packages/now-python/index.js
See: https://stackoverflow.com/a/44728772/376773
The `setup.cfg` is required for `now dev` on MacOS, where without this file being present in the src dir then this error happens:
```
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```
=> [now-python] Add `setup.cfg` file before running `pip install`

packages/now-go/go-helpers.js
This fixes a subtle bug in the `getExportedFunctionName()` helper function.
It wasn't actually causing any issues in production, since the `index.js` file also does `await` on the return value of this function so it was still resolving the promise properly, but this is more correct and fixes the associated `debug()` call.
=> [now-go] Add missing await to `getExportedFunctionName()`

test/lib/deployment/test-deployment.js
Since the prepublish script for `@now/node` writes other stuff to stdout, so relying on `npm pack` outputting the tarball name is not reliable.
Instead, just `glob()` for a `*.tgz` file and expect that to be the output package tarball.
Fixes error:
```
Error: ENOENT: no such file or directory, open '/home/circleci/repo/packages/now-node/> @now/node@0.5.2-canary.2 prepublish /home/circleci/repo/packages/now-node
> npm run build
> @now/node@0.5.2-canary.2 build /home/circleci/repo/packages/now-node
> ./build.sh
'/home/circleci/repo/packages/now-node-bridge/bridge.d.ts' -> 'src/bridge.d.ts'
now-node-0.5.2-canary.2.tgz'
```
=> Fix `packAndDeploy()` for usage with `@now/node`

packages/now-python/index.js
Otherwise the `setup.cfg` file is not respected (see #292).
=> [now-python] Run `pip` from within the installation directory

packages/now-python/now_handler.py
Similar to #224, but for Python.
=> [now-python] Bind HTTP server to an ephemeral port

packages/now-node-server/index.js, packages/now-node/src/index.ts
[now-node] Bump `@zeit/ncc` to version 0.16.1 which includes fixes for webpack asset loader
=> [now-node] Bump ncc to 0.16.1

packages/now-md/index.js
Not sure why this was here, but it's pretty noisey in the logs,
especially when executing this builder via `now dev`.
=> [now-md] Remove `console.log()` call of Markdown file result

packages/now-rust/Cargo.lock, packages/now-rust/Cargo.toml
Already published at https://crates.io/crates/now_lambda/0.1.3
=> Publish now_lambda 0.1.3

packages/now-node-server/index.js, packages/now-node-server/test/fixtures/11-include-files/index.js, packages/now-node-server/test/fixtures/11-include-files/now.json, packages/now-node-server/test/fixtures/11-include-files/package.json, packages/now-node-server/test/fixtures/11-include-files/templates/index.html
The main idea behind this is we want user be able to specific files in that should be include in the `handler` which later can be use in runtime.
For the most case, `ncc` be able to detect relevant files included in the `handler`. But the case that `ncc` not able to resolve, this option come in handy.
PR #277 does the same thing, but for `@now/node`.
=> [now-node-server] Add `config.includeFiles`

packages/now-bash/package.json, packages/now-node/src/index.ts, packages/now-node/test/fixtures/09-include-files/index.js, packages/now-node/test/fixtures/09-include-files/now.json, packages/now-node/test/fixtures/09-include-files/package.json, packages/now-node/test/fixtures/09-include-files/templates/index.edge
if `bundle` provide in `config` object, then all of the files will be bundle with `handler`.
This fixes [this problem](https://spectrum.chat/zeit/now/reading-template-assets-on-file-system-using-now-node~56f167d9-7416-444f-a352-6738b341df48) when template files (assets) are not included in the output.
=> [now-node] Add `config.includeFiles`

packages/now-html-minifier/index.js
`collapseInlineTagWhitespace` removes white space between inline elements so `<p>Text with <a href="https://zeit.co/now">a link</a> is hard to read.</p>` renders as `Text witha linkis hard to read.`
See example at https://runkit.com/5c8a1c7a0f950f0012252fbb/5c8a1c7a0f950f0012252fbc
It's probably safe to keep the `collapseWhitespace` option for now but [it can also affect document rendering](http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace).
=> [now-html-minifier] Remove collapseInlineTagWhitespace option

packages/now-go/index.js
With our current example: https://zeit.co/docs/v2/deployments/official-builders/go-now-go/#how-to-use-it
`@now/go` build will fail if user don't provide `go.mod`. This happen because command `go mod init packageName` not working as intended.
Ultimately, we just want something like this in default `go.mod` file
```
module defaultName
```
So I use `writeFile()` function to create that file instead.
=> [now-go] better way to init go.mod

test/lib/deployment/now-deploy.js
This PR adds tracing priority to our tests so we will have some backend visibility into which service/method call was slow during an integration test.
PS: looks like the linter changes more lines than I intended.
Here we can see proof of the tests being traced during that 10 minute interval.
=> Add tracing priority to tests

packages/now-build-utils/src/download.ts, packages/now-build-utils/src/file-blob.ts, packages/now-build-utils/src/fs/glob.ts, packages/now-build-utils/src/index.ts, packages/now-build-utils/src/types.ts, packages/now-node-bridge/tsconfig.json, packages/now-node/src/index.ts, packages/now-node/tsconfig.json
This adds a few new exports to `@now/build-utils` with proper documentation 😄 
- AnalyzeOptions
- BuildOptions
- PrepareCacheOptions
I also updated TS is `now-node` and `now-node-bridge`.
Here's an example of what the docs look like with TS Intellisense 📖
=> Enhance TS declarations

packages/now-node/src/launcher.ts
This fixes the dreaded `Unable to import module 'launcher'` error message. If this looks good then we can add it to `@now/node-server` as well.
**Before:**
**After:**
=> [now-node] Print a more helpful message when a module is missing

packages/now-node-server/launcher.js
Similar to #312, but for `@now/node-server`.
=> [now-node-server] Print a more helpful message when a module is missing

packages/now-python/index.js
Instead of generating another temp directory.
=> [now-python] Use `workDir` provided by builder

packages/now-build-utils/package.json, yarn.lock
All of the other deps are pinned versions, so this is for consistency.
=> [now-build-utils] Pin "end-of-stream" dependency to v1.4.1

packages/now-build-utils/src/file-blob.ts, packages/now-build-utils/src/file-fs-ref.ts, packages/now-build-utils/src/file-ref.ts, packages/now-build-utils/src/lambda.ts
This is important for TypeScript usage with the combined `File` type
declaration. It helps the compiler understand the proper type in
consuming code via `if` checks to avoid casting.
=> [now-built-utils] Use constants for the `type` field

packages/now-node-server/index.js, packages/now-node/src/index.ts
This bumps ncc to `0.17.0` for node builders
See the release notes here: https://github.com/zeit/ncc/releases/tag/0.17.0
=> [now-node] Bump ncc to 0.17.0

packages/now-rust/index.js, packages/now-rust/package.json, packages/now-rust/test/fixtures/01-include-files/Cargo.lock, packages/now-rust/test/fixtures/01-include-files/Cargo.toml, packages/now-rust/test/fixtures/01-include-files/now.json, packages/now-rust/test/fixtures/01-include-files/src/main.rs, packages/now-rust/test/fixtures/01-include-files/static/sample.txt, packages/now-rust/test/test.js
This add the ability to include other files into the filesystem of the lambda. This works by providing an `includeFiles` option in the builder config, and then moving those into the lambda when it's created. The `includeFiles` option is a glob matcher relative to the entrypoint.
**Note:** This is the first example I know of that allows a user to add more files to the filesystem through the official now builders. This API is something I came up with, and may not be the best or what y'all are thinking.
This is helpful for my specific case, where I need extra binaries on the system when the lambda executes (`wget` and `now`). This could also be useful to include large files to parse, or other things one wouldn't want to include in the rust binary itself due to file size, memory allocation, …
=> [now-rust] Allow extra static files on the lambda fs `config.includeFiles`

packages/now-bash/bootstrap, packages/now-bash/runtime.sh
* Send error responses with `errorMessage` property, so that `now dev` can display the error message properly.
* Add shebang to `runtime.sh`, so that vim applies proper syntax highlighting when bash-specific features like `<<<` are used.
* Add shellcheck ignore comments to dynamic imports (shellcheck is now passing).
=> [now-bash] Improvements for error handling

test/lib/deployment/now-deploy.js
This will generate a new token for every 10 API call so we stop getting rate limited.
=> Fix rate limit for tests

packages/now-go/index.js, packages/now-go/test/fixtures/01-cowsay/index.go, packages/now-go/test/fixtures/01-cowsay/now.json, packages/now-go/test/fixtures/01-cowsay/subdirectory/index.go, packages/now-go/test/test.js
**Back story**
In the process of write test case for `@now/go`, I found this bug. It was introduce with `go.mod` release.
**How build work?**
Given `entrypoint` is `index.go`:
```go
package handler
import (
"fmt"
"net/http"
)
func Handler(w http.ResponseWriter, r *http.Request) {
fmt.Fprintf(w, "<h1>Hello from Go on Now!</h1>")
}
```
Before we run command `go build`, we move `entrypoint` to folder (using package name as folder name). Then our main go file will look like this:
```go
package main
import (
"net/http"
"function/function"
now "github.com/zeit/now-builders/utils/go/bridge"
)
func main() {
now.Start(http.HandlerFunc(function.Handler))
}
```
**What went wrong?**
When we move `entrypoint` to folder, we had this as destination
```
join(entrypointDirname, packageName, entrypoint) …
```
=> [now-go] fix subdirectory build fail for `@now/go`

packages/now-next/index.js
This pull request makes `@now/next` compatible with `now dev` (emitting debug production builds and building individual pages).
~We should finish implementing `subscription()` before merging this. Also, these changes require Next.js `>=8.0.5-canary.2` so we should probably handle that.~
---
~We still need to get rid of build ID for this to work correctly. We'll require a newer Next.js canary for this.~
=> Make @now/next compatible with `now dev`

packages/now-build-utils/src/fs/run-user-scripts.ts
`cache clean` was being invoked for legacy purposes back when we were
dealing with Lambda's 500mb runtime filesystem limit. Now that builds
are not running on lambda, this can be removed. It also makes `now dev`
building unnecessarily slow.
=> [now-build-utils] Remove yarn/npm cache clean after install

packages/now-next/index.js, packages/now-next/package.json
The subscribe function expects `about` but we give it `pages/about`
Catch errors with semver
Static files don't have a leading slash
=> @now/next hotfixes for `now dev` optimizations

packages/now-next/index.js, packages/now-next/package.json, yarn.lock
`^8.0.5-canary.8` didn't work while `8.0.5-canary.8` and `canary` did.
=> [now-next] Strip Carat from version

packages/now-mdx-deck/index.js, packages/now-next/index.js, packages/now-node-server/index.js, packages/now-node/src/index.ts
Considering that `prepareCache()` is executed directly after `build()` is run, it seems that deleting the previous `workPath` and re-installing the dependencies is just extra work, and it would be better to create a cache from the `workPath` artifacts that `build()` just created.
From the perspective of `now dev`, this is ideal because:
1. The `workPath` shouldn't be deleted since static file assets are served from the `workPath`, so `prepareCache()` deleting this directory is problematic.
2. Creating the cache quickly becomes an important goal, because it reflects how quickly a developer can iterate on a file, and we don't want them waiting for `yarn` to finish installing dependencies all the time in order to see the change in their project.
=> Update `prepareCache()` functions to use existing `workPath`

packages/now-static-build/index.js
Fix link to documentation in static builder when the `dist` directory is not created.
I also changed the `build-utils` to use top-level imports like our docs specify.
=> [now-static-build] fix link to docs

packages/now-node-bridge/src/bridge.ts
If the `http.Server` handler function throws an error asynchronously, then it ends up being an unhandled rejection which doesn't kill the node process which causes the HTTP request to hang indefinitely. So print the error here and force the process to exit so that the lambda invocation returns an `Unhandled` error quickly.
=> [now-node-bridge] Exit the Node.js process upon `unhandledRejection`

packages/now-node-server/index.js, packages/now-node-server/launcher.js, packages/now-node-server/package.json, packages/now-node/package.json, packages/now-node/src/index.ts, packages/now-node/src/launcher.ts, yarn.lock
This PR moves the installation of `ncc` from `build` function to `npm install` stage of the whole builder. This is needed for further caching approach being developed now.
=> now/node: move ncc to npm dependencies

packages/now-build-utils/src/file-fs-ref.ts
This is the more proper fix for #373.
=> [now-build-utils] Set the `mode` when creating the file, not afterwards

packages/now-next/index.js
This feature isn't landed in Next.js yet -- but this is the path it'll use.
We should land this and get it out in a canary sooner than later, so it "just works" with newer Next.js versions.
=> [now-next] Cache Flying Shuttle directory

packages/now-next/index.js, packages/now-next/package.json
Next.js will now cache under the `.next/cache` folder. We should pass these contents to the `n+1` build.
=> [now-next] Cache the new Next.js cache location

packages/now-build-utils/src/file-ref.ts
Not all files are cacheable (and our default CloudFront configuration assumes this), e.g. builder cache archives.
This PR adds an `immutable` option to `FileRef` (default `true`) -- setting `immutable: false` will download the file fresh from S3.
=> Add a `mutable` flag to FileRef

packages/now-build-utils/.gitignore, packages/now-build-utils/package.json, packages/now-build-utils/src/lambda.ts, packages/now-build-utils/test/test.js
After #359, creating zip files with symlinks would be corrupted because the "target" of the symlink was actually the file contents.
This commit fixes the zip file construction logic to handle symlinks by placing the target of the symlink as the "contents" of the file in the zip. The unit test relies on GNU `unzip` and checks that it creates the symlink from the produced zip file as expected.
=> [now-build-utils] Create zip files with symlinks properly

test/lib/deployment/now-deploy.js, test/lib/deployment/test-deployment.js
This is a quick fix for our token problem by attempting to retry the fetch.
> FetchError: invalid json response body at NOW_TOKEN_FACTORY_URL reason: Unexpected token A in JSON at position 0
The root cause is in the token factory because it throws `Confirmation incomplete` but that will be harder to track down and fix.
=> Add fetchTokenWithRetry for bad json response

packages/now-next/package.json, packages/now-next/src/index.ts
Like this, we ensure that no `routes` are provided as long as `next dev` is not running.
=> Wait for Next.js dev server to run before continuing

packages/now-next/src/index.ts
The property `continuous` was renamed to `requiresInitialBuild` in https://github.com/zeit/now-cli/pull/2199.
=> Renamed property that has changed its name

packages/now-node-server/package.json, packages/now-node/package.json, packages/now-node/test/fixtures/14-stack-trace-ts/now.json, packages/now-node/test/fixtures/14-stack-trace-ts/tsconfig.json, yarn.lock
This bumps `@zeit/ncc` to the latest version which fixes source maps for TypeScript. 
I also updated the `14-stack-trace-ts` test to be accurate. When I added this test originally, it was off by 2 lines just because it was better than off by 50 lines. Now we show the proper line number 🎉
=> [now-node] Bump ncc to 0.18.1

packages/now-next/package.json, packages/now-next/src/dev-server.ts, packages/now-next/src/index.ts, packages/now-next/src/utils.ts
Currently, `next dev` is starting inside the `cwd` of the `entrypoint`. Since that leaves behind nasty temporary files, we decided to move it into the `workPath`.
=> Develop Next.js app inside workPath

packages/now-next/package.json, packages/now-next/src/dev-server.ts, packages/now-next/src/index.ts, yarn.lock
This makes the builder be able to invoke Next.js dev properly on macOS.
=> Make `@now/next` dev work on macOS

packages/now-next/src/index.ts, packages/now-next/test/unit/build.test.js
I changed the return type to include `childProcesses` so that tests can properly shutdown the dev server.
=> Add builder v2 tests to @now/next

packages/now-build-utils/src/fs/run-user-scripts.ts
To allow, for example, setting `env` variable.
=> [now-build-utils] Allow build options for `runPackageJsonScript()`

packages/now-build-utils/src/fs/download.ts
Like this, we're not re-downloading files that didn't change.
**It's only missing deletion of files.**
=> Make `download()` dedupe

.prettierrc.json, package.json, packages/now-next/src/index.ts
- fixed Prettier not running for TypeScript files
- adjusted Prettier config to match ESLint better (trailing comma)
- increased user script heap size to system memory - `128mb` reserve
Line of interest: https://github.com/zeit/now-builders/pull/419/files#diff-a4e14c2c5a53127f6f33ece5e544e848R254
=> Increase heap size for Next.js builds

packages/now-next/src/index.ts
This makes https://github.com/zeit/now-builders/pull/416 work.
=> Pass `meta` to `download()` of `@now/next`

packages/now-next/src/index.ts
Set `__NEXT_BUILDER_EXPERIMENTAL_TARGET` to `serverless` so the user doesn't need to set it manually
=> Set target env variable

packages/now-static-build/index.js, packages/now-static-build/package.json, yarn.lock
This will cause `now dev` to run the `now-dev` script as defined in the `package.json` file.
`now dev` sets the `PORT` env variable for use in the `now-dev` script, which is expected to launch a file watching server (for example `hugo dev`) on the specified `$PORT`. `now dev` wait for this port to be bound before returning the `build()` function with the generated assets.
The `watch` array is just "watch everything in the `path.dirname(entrypoint)`" so any file changed within that directory will trigger a "re-sync" of the source files that `now dev` is working with, which the user spawned static build watcher should pick up on and return the updated assets.
Depends on https://github.com/zeit/now-builders/pull/417 in order to pass the `PORT` env var to the `now-dev` script.
Depends on …
=> [now-static-build] Add `now-dev` package.json script

packages/now-build-utils/src/types.ts
The `workPath` property was missing from the `ShouldServeOptions`.
=> Added missing `workPath` type property

packages/now-build-utils/src/types.ts
This will make it clear the `fsPath` is an absolute path, not a relative path.
=> Add comment to fsPath about absolute path

packages/now-go/util/analyze.go
Better checking for not `entrypoint` go source files.
=> [now-go] Using full path for checking against `entrypoint`

packages/now-go/go-helpers.ts, packages/now-go/index.ts
Fixes #130
https://golang.org/cmd/link/
* `-s`: Omit the symbol table and debug information.
* `-w`: Omit the DWARF symbol table.
=> [now-go] Use optimized build flags

packages/now-static-build/index.js, packages/now-static-build/package.json
This is an alternative approach to detecting when the dev server is ready to receive HTTP traffic, also bumps the timeout to 5 minutes.
=> [now-build-utils] Wait for the dev server to print the URL with correct port number

packages/now-go/go-helpers.ts, packages/now-go/index.ts
This will make `@now/go` faster for `now dev`.
- if user have `Go` in their dev machine, we use that.
- if user don't have `Go`, download it once, and reuse it.
=> [now-go] Improve speed for `now dev`

packages/now-static-build/index.js
This will print a warning so that the user knows about the `now-dev` script in package.json is the preferred way to develop.
=> [now-static-build] Warn when now-dev script is missing

packages/now-build-utils/package.json, packages/now-build-utils/src/fs/run-user-scripts.ts, yarn.lock
Fixes `spawn yarn ENOENT` issues when running `now dev` on Windows.
=> [now-build-utils] Use `cross-spawn` for Windows support

packages/now-node/src/index.ts, packages/now-node/test/fixtures/09-include-files/accepts-string.js, packages/now-node/test/fixtures/09-include-files/now.json, packages/now-node/test/fixtures/09-include-files/templates/accepts-string.edge
For the record, most of the changes in `index.ts` have been made automatically by the linter. Actual modifications I've made are located at lines [17](https://github.com/flawyte/now-builders/blob/bea5dee215ff5f7386fde456d4a00db4712b9d91/packages/now-node/src/index.ts#L17) and [59-64](https://github.com/flawyte/now-builders/blob/bea5dee215ff5f7386fde456d4a00db4712b9d91/packages/now-node/src/index.ts#L59-L64).
I could have refactored the code in the loop to an independent function that would be called directly if `includeFiles` is a string, and otherwise called within the loop, but I though that just turning `includeFiles` into an array if it's a string and then let the loop do the job like before would be simpler and overall better.
Please let me know if there's anything missing.
=> [now-node] 'config.includeFiles' accepts a string

packages/now-static-build/index.js
Hi, I have encountered an issue with @now/static-build described at https://spectrum.chat/zeit/now/issue-with-now-static-build-builder~08b8ad28-bbba-47a0-82e8-812cdcc65cc6
TL/DR, when package.json resides in a directory, `now dev` fails.
I _think_ I have found the issue, but I would need help testing it guys. I literally have no idea how testing this might work.
Thanks!
=> [now-static-build] Fix @now/static-build nested build

packages/now-bash/index.js, packages/now-cgi/index.js, packages/now-html-minifier/index.js, packages/now-lambda/index.js, packages/now-md/index.js, packages/now-node-server/index.js, packages/now-node/src/index.ts, packages/now-optipng/src/index.ts, packages/now-php/index.js, packages/now-python/index.ts, packages/now-rust/index.js
This adds the default `shouldServe()` implementation to the following builders:
* `@now/bash`
* `@now/cgi`
* `@now/html-minifier`
* `@now/lambda`
* `@now/md`
* `@now/node-server`
* `@now/node`
* `@now/optipng`
* `@now/php`
* `@now/python`
* `@now/rust`
The default implementation may be used for these builders because they map 1-1 with their entrypoint file -> output file/lambda.
=> Add default `shouldServe()` to appropriate builders

packages/now-build-utils/src/fs/run-user-scripts.ts, packages/now-build-utils/test/fixtures/15-yarn-ignore-engines/index.js, packages/now-build-utils/test/fixtures/15-yarn-ignore-engines/now.json, packages/now-build-utils/test/fixtures/15-yarn-ignore-engines/package.json
This solves the problem where a google dependency such as `@google-cloud/scheduler` depends on a package that is incompatible with Node 8.10
The error looks like the following:
```
error @grpc/grpc-js@0.3.6: The engine "node" is incompatible with this module. Expected version "^8.11.2 || >=9.4". Got "8.10.0"
error Found incompatible module
```
The reason why we can ignore `engines` is because this check happens at install time, even if the transient dependency is unused and not bundled with `ncc`. So it is best to let the build continue and fail at runtime if the package is incompatible with the current Node version.
Related to #273
=> [now-build-utils] Add `yarn --ignore-engines` during install

packages/now-node-server/package.json, packages/now-node/package.json, yarn.lock
Update to latest version `@zeit/ncc` to [0.18.3](https://github.com/zeit/ncc/releases/tag/0.18.3).
This truncates the output during build errors so that only the error is shown, not the warning.
=> [now-node] Bump ncc to 0.18.3

packages/now-build-utils/src/fs/download.ts
This will be necessary for the update in `now dev` to have the builder `workPath` be equal to the `cwd` source directory of the dev server.
Otherwise, unnecessary file modifications are made (copying the source file to itself) and file corruption often occurs.
=> [now-build-utils] Make `download()` a no-op in `now dev`

packages/now-node/src/index.ts
Depends on https://github.com/zeit/now-builders/pull/474.
=> [now-node] Pass in the `meta` object to `download()`

.gitignore
The `coverage` should not be committed and it causes errors like this one during publish: https://circleci.com/gh/zeit/now-builders/1857
```
$ lerna publish from-git --npm-tag canary --yes
lerna notice cli v3.5.0
lerna info versioning independent
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/whoami 565ms
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```
I also added `*.tgz` just in case.
=> Add coverage to `.gitignore`

packages/now-php/index.js
It's not clear to me why we were installing to `userfiles` directory, so let me know if this breaks something.
=> [now-php] Download files to `workPath` and pass `meta`

packages/now-next/src/launcher.ts
This makes sure that https://github.com/zeit/next.js/pull/7296 can be deployed.
Without this PR it would build correctly but then fail at runtime (because `.render` is called)
=> [now-next] Add support for /api routes

errors/now-static-build-failed-to-detect-a-server.md, packages/now-static-build/index.js
The error message alone doesn't explain how to fix it, so adding this `err.sh` link to guide the user to instructions on how to fix it.
For example: https://github.com/zeit/now-cli/issues/2339
=> [now-static-build] Add `err.sh` link when dev server detection fails

packages/now-static-build/index.js
The `srcBase` (directory where the entrypoint is located) should not be in the `dest` proxy pass URL.
Consider an entrypoint like `blog/package.json`. The development server will be running within the `blog` directory. A request for `GET /blog/static/foo.js` comes in, so we want to proxy pass to `http://localhost:12345/static/foo.js` rather than `http://localhost:12345/blog/static/foo.js` which would lead to a 404.
=> [now-static-build] Remove `srcBase` from the proxy pass destination

packages/now-go/util/analyze.go
This commit adds some changes to the way the AST for the source is
built.
The `analyze.go` program now ignores every `vendor`, `.git` and
`testdata` folder. This improves performance, since `vendor` and `.git`
are usually large folders (#504).
By ignoring `testdata`, we mimick the behaviour of `go build` and avoid
failing the parsing because of invalid Go code inside of `testdata` (#503)
=> [now-go] Ignore folders in `analyze.go` (#503)(#504)

packages/now-go/index.ts, packages/now-go/util/analyze.go
Use `meta` in `download()`. I have to do some tricks to handle `cwd/.now`.
You can try it out here `now-go-test-cwd`
=> [now-go] Use meta in `download()`

jest.config.js
With this PR, we ensure only the tests for packages that changed are run.
If no packages changed, the tests for `now-node` are run to see if the testing infrastructure still works after the change the commit author made.
For example, this is the log for the current PR:
If a change was made, this is how it would look:
=> Run only tests for packages that changed

packages/now-node-bridge/src/bridge.ts, packages/now-node-bridge/test/bridge.test.js
It has been requested several times that we should set [callbackWaitsForEmptyEventLoop](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html#nodejs-prog-model-context-properties) to false.
However, I didn't add a test because we don't have any examples of failing code.
Perhaps @joecohens can provide an example.
=> [now-node-bridge] Disable callbackWaitsForEmptyEventLoop

packages/now-next/src/index.ts
In the latest Next.js we auto export static pages to HTML when enabled. This adds handling of those created HTML files.
=> [now-next] Handle statically exported pages

packages/now-next/src/index.ts
Since just specifying the pages in `output` causes them to be downloaded. This specifies the static pages under routes.
=> [now-next] Update to use routes for static pages

packages/now-go/index.ts
This PR will add support private git repos.
Fixes #316 
This environment variable needs to be in the build instead of the runtime like this in `now.json`:
```json
{
"build": {
"env": {
"GIT_CREDENTIALS": "https://username:token@github.com"
}
}
}
```
Supports any Git provider (GitHub, Bitbucket, GitLab) as well as self-host Git server.
=> [now-go] Add option to use private Git for `go get`

package.json
Going forward, the default branch is now `canary`.
New PRs should be submitted to the `canary` branch. We will publish canary builders from the canary branch.
Periodically we will merge `canary` into `master` and publish stable releases.
This PR will make sure we publish from the correct branch.
=> Switch branch during publish

packages/now-rust/index.js
Avoid installing rust and openssl during development since these should already be installed by the user.
Doc updates [docs#863](https://github.com/zeit/docs/pull/863)
Fixes [now-cli#2087](https://github.com/zeit/now-cli/issues/2087)
=> [now-rust] Don't try and install rust and openssl during development

packages/now-rust/index.js
PR #532 was accidentally merged into `master` instead of `canary`.
This makes sure we have this change on canary branch.
@mike-engel In the future, PRs should be submitted to `canary` branch.
=> Merge master into canary

packages/now-go/index.ts
Fixes #528
I go with show error message approach rather than update the `entrypoint` src file for user. I think it more concrete this way, letting user know exactly what's happened.
Let me know your thought on this 🙏
=> [now-go] Show error when using `package main` with `go.mod`

.circleci/config.yml, .circleci/publish.sh, .github/main.workflow, package.json
Non-ZEIT Members are unable to run Circle CI for security purposes, in particular the npm publish step.
This PR moves the publish step from Circle CI to GitHub Actions so that we can enable Circle CI for everyone!
=> Use GitHub Actions for publishing to npm

packages/now-python/index.ts
There is a message that displays for each `pip install` that is useless for the end user since they don't choose a pip version right now.
```
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
This PR disables that message by using `pip install --disable-pip-version-check`.
=> [now-python] Disable pip upgrade notice

.github/main.workflow
There seems to be a bug with GitHub Actions running twice when a PR is merged. I suspect that deleting the branch is triggering an additional workflow.
This change will ensure the branch is canary AND the push was not a deleted branch.
=> [tests] Fix duplicate GH Actions

packages/now-static-build/index.js
This pull request updates the @now/static-build docs link for local development.
=> Fix static-build local development docs link

packages/now-go/util/analyze.go
This should be fix the parse fail bug for `entrypoint` that in subdirectory that doesn't contain `go.mod`.
=> [now-go] Fix subdirectory parse fail

.github/CODEOWNERS
Because @Timer is 🥇 
Also because I am not involved in most Next.js discussions so no reason for me to review the PRs.
=> [now-next] Add timer to codeowners

packages/now-next/src/index.ts
Since, auto exported pages can be dynamic pages now this adds generating of dynamic routes for them in a production build
=> [now-next] Add generating of dynamic routes for auto exported pages

packages/now-next/src/index.ts
Makes sure `/$post` becomes `/$post.html` for auto exported dynamic routes
=> [now-next] Make sure `.html` is appended to dynamic auto exported routes

packages/now-next/src/index.ts
Next.js users expect their 404 page to be rendered when deploying to Now.
=> [now-next] Route 404 to custom Next.js error page

packages/now-layer-node/src/index.ts, packages/now-layer-node/src/install.ts, packages/now-layer-node/test/test.js, packages/now-layer-npm/src/index.ts, packages/now-layer-npm/src/install.ts, packages/now-layer-npm/test/test.js, packages/now-layer-yarn/src/index.ts, packages/now-layer-yarn/src/install.ts, packages/now-layer-yarn/test/test.js
This adds `entrypoint` to the return result of each layer which contains a path to the entrypoint, for example the binary for Node or the script for Yarn.
In a future PR, we might want to move this new interface to the `@now/build-utils` package to make it easier to write type safe layers.
=> [now-layer] Add entrypoint to BuildLayerResult

packages/now-python/package.json
This change never made it to master and broke the stable release.
I also changed `prepublishOnly` just to make sure it's different.
=> Fix python

README.md, package.json
Thanks to @leo for the instructions, we will now follow the same [canary cherry-pick](https://leo.im/2017/canary/) workflow that `now-cli` and `now-desktop` follow.
I also added markdown files to the prettier lint step.
=> Update publish instructions in the README

test/lib/deployment/test-deployment.js
https://github.com/zeit/now-builders/blob/65afda101f849908097c6f7577dc73e3d36d9960/test/lib/deployment/test-deployment.js#L85-L91
These lines were always sending a `content-type: application/json` header, even if the body is `undefined`.
This PR aims at fixing this.
=> Fix `content-type: application/json` header being added even if body is `undefined`

packages/now-rust/index.ts
`config.includeFiles` can be of type `string[]`.
Example in the fixtures :
https://github.com/zeit/now-builders/blob/6aeda0363a461069608d0b913bed467525b6feb4/packages/now-rust/test/fixtures/01-include-files/now.json#L8
It is passed to `gatherExtraFiles` as `globMatcher` which had an incorrect type.
=> [now-rust] config.includeFiles can be `string[]`

packages/now-node/jest.config.js, packages/now-node/package.json, packages/now-node/src/helpers.ts, packages/now-node/test/helpers.test.ts, packages/now-node/tsconfig.json, yarn.lock
This PR :
- translate existing helpers tests in ts
- make tests fail if types `NowRequest` and `NowResponse` are not exported from `index.ts`
=> [now-node] Add tests for types exports

packages/now-node/src/index.ts, packages/now-node/test/fixtures/15-helpers/now.json
PR #577 (released in `@now/node0.8.0`) broke body parsing when using `micro` and other packages.
I have since moved the `latest` dist-tag back to `0.7.4`.
This PR changes the `helpers` config to be opt-in until we can figure out a proper fix on Monday.
If we merge this in soon, I can do another release as `@now/node0.8.1`.
=> [now-node] Change helpers to opt-in

packages/now-next/src/index.ts
Updates check to make sure it checks without leading slash. Tested at `@ijjk/now-next@0.0.1-dev.7` Example project [here](https://dynamic.jj4.now.sh)
=> [now-next] Update appending of `.html` to auto exported routes

packages/now-static-build/index.js, packages/now-static-build/test/fixtures/05-empty-dist-dir/now.json, packages/now-static-build/test/fixtures/05-empty-dist-dir/package.json, packages/now-static-build/test/fixtures/06-missing-script/now.json, packages/now-static-build/test/fixtures/06-missing-script/package.json, packages/now-static-build/test/test.js
Fixes #8 so that the build fails immediately if the `config.distDir` is not a directory or if the `config.distDir` is empty.
Before this PR, the only validation was to check if `distDir` exists (which is still there).
I also updated the error message so that it links to the Local Development section if using `now dev`.
Lastly, I added tests so we don't regress.
=> [now-static-build] Should fail build when distDir is empty

packages/now-node-bridge/src/bridge.ts, packages/now-node-bridge/test/bridge.test.js
This PR is the `now-node-bridge` part of https://github.com/zeit/now-builders/pull/594.
To be able to add `req.body` in listeners and keep compat with express, micro, etc..., we need to make normalized events consumable by a server.
We add a second argument to bridge constructor :
```js
new Bridge(server, true)
// second argument tells bridge to store normalized events
// and send a reqId in `x-now-bridge-request-id` header to consume it
```
Events can be consumed like this :
```js
const event = bridge.consumeEvent(reqId)
```
=> [now-node-bridge] Make normalized events consumable by server

packages/now-node/src/index.ts, packages/now-node/test/fixtures/15-helpers/now.json
Now that helpers are not breaking existing applications (https://github.com/zeit/now-builders/pull/594), we can make helpers opt-out again.
=> [now-node] Make helpers opt-out instead of opt-in

packages/now-node/package.json, packages/now-node/src/helpers.ts
We export `NowRequest` and `NowResponse` types that depends on `@types/node` from `@now/node`.
`@types/node` is moved to dependencies for this reason.
=> [now-node] Move `@types/node` to dependencies

packages/now-node/src/helpers.ts
Add type casting for `req.headers.cookie` as `string | string[] | undefined` to avoid regression.
=> [now-node] Assign type for `req.headers.cookie`

packages/now-next/src/index.ts
We now store the `.next/cache` folder so we need to check for the `static` folder to know if the user uploaded something they should've excluded.
---
Fixes https://github.com/zeit/now-builders/issues/605
=> [now-next] Fix erroneous `.next` folder message

packages/now-next/src/index.ts
Some users read this message as a warning that required action (the captain caps lock WARNING didn't help).
Users should never need to define a `now-build` script unless they grow out of running `next build`.
Fixes #363
=> [now-next] Humanize message about `now-build`

packages/now-node/src/helpers.ts, packages/now-node/src/types.ts, packages/now-node/test/helpers.test.js
This PR brings a set of improvements to `@now/node`:
=> [now-node] Improve `@now/node` helpers

jest.config.js
As a follow up to #515, this enhancement will make sure we run tests for all the commits in a branch in a PR. We had some cases where the squashed merge to master failed tests even though they passed in the PR. This should fix that.
Previously, tests would only run for the most recent commit which will remain the same way for the master branch.
=> [tests] Run against all commits in the branch

packages/now-node/src/helpers.ts, packages/now-node/test/helpers.test.js
This PR aims at fixing the edge case where a request is sent and :
- content-type is `application/json`
- body is empty (no body or '')
Previously, `req.body` would be `undefined`. After this PR, request fails with `400 Invalid JSON` error.
=> [now-node] Fix faulty behavior when request's body is empty and content-type is `application/json`

packages/now-go/index.ts, packages/now-go/test/fixtures/13-go-mod-nested/api/nested/index.go, packages/now-go/test/fixtures/13-go-mod-nested/go.mod, packages/now-go/test/fixtures/13-go-mod-nested/now.json, packages/now-go/test/fixtures/13-go-mod-nested/shared/shared.go
This PR added support for nested packages. This requested by many of our `@now/go` users.
Might related:
- https://github.com/zeit/now-builders/issues/431#issuecomment-500235805
- https://spectrum.chat/zeit/now/now-go-no-longer-builds-project-with-multiple-go-handlers~854b8f25-3a40-4d68-820f-4b6a377ccf81
- https://spectrum.chat/zeit/now/how-to-share-common-code-in-two-handlers-in-go-deployed-on-now~71966eec-8bcb-456a-b666-2d4610c19dc9
- https://spectrum.chat/zeit/now/using-modules-with-golang~c982d06c-aea3-4ad8-839c-4c13878450b4
=> [now-go] add support for nested packages

yarn.lock
This is a follow up to #617.
Seems like some tests were having issues so this cleans up the yarn.lock file.
=> [tests] Fix yarn.lock

packages/now-build-utils/package.json, packages/now-go/package.json, packages/now-next/package.json, packages/now-node-bridge/package.json, packages/now-node/package.json, packages/now-optipng/package.json, packages/now-python/package.json, packages/now-rust/package.json, yarn.lock
This consolidates all the typescript dependencies to the latest 3.5.2 version.
cc @bluelovers
Closes #616
=> [tests] Bump typescript to 3.5.2

packages/now-go/index.ts, packages/now-go/test/fixtures/14-go-mod-sub/api/index.go, packages/now-go/test/fixtures/14-go-mod-sub/now.json, packages/now-go/test/fixtures/14-go-mod-sub/other-folder/go.mod, packages/now-go/test/fixtures/14-go-mod-sub/other-folder/index.go
If the directory structure is the following:
```
/api/index.go
/other-folder/index.go
/other-folder/go.mod
```
Then the build will fail.
Build would fail because `isGoModExist` would be set to true without `goModPath` being filled.
This PR fixes that.
=> [now-go] Fix failing build when go.mod exists in a subfolder

packages/now-build-utils/src/fs/run-user-scripts.ts
This is necessary to assign the `PATH` to the correct Node version (this will be enabled in a future PR).
Related to #500
=> [now-build-utils] Add spawnOpts param to `runNpmInstall()`

packages/now-ruby/package.json
The `@now/ruby` builder was missing `typescript` as a dependency so `tsc` didn't work
=> [now-ruby] Fix ruby publish step

packages/now-node/src/index.ts
This ensures the build environment matches the runtime environment when engines matches Node 10 for running `npm install` as well as `npm run <script>`.
Related to #500 
Related to #273
=> [now-node] Change PATH to use node10

packages/now-node/package.json, packages/now-node/src/helpers.ts, packages/now-node/src/types.ts, packages/now-node/test/helpers.test.js, yarn.lock
Express is adding properties on `req` and `res` objects by doing the following:
```js
Object.setPrototypeOf(req, newRequestProto)
Object.setPrototypeOf(res, newResponseProto)
```
(the actual code is here : https://github.com/expressjs/express/blob/e1b45ebd050b6f06aa38cda5aaf0c21708b0c71e/lib/application.js#L231-L232)
This means that properties defined directly on `req` and `res` won't be overriden by express.
To solve that, this PR sets the properties on `req.__proto__` and `res.__proto__`.
=> [now-node] Fix express not overriding helpers properties

packages/now-build-utils/src/fs/node-version.ts, packages/now-build-utils/src/fs/run-user-scripts.ts, packages/now-build-utils/src/index.ts, packages/now-build-utils/src/types.ts, packages/now-build-utils/test/test.js
This PR moves some of the Node version selection logic into `@now/build-utils` so it can be reused in several of our Official Builders.
The public interface changes are the following:
There are basically 3 things that can happen in `getNodeVersion`:
- missing `engines`, using default
- found `engines` but does not match, using default
- found `engines`, using matching version
The returned value can be used to find the runtime as well as spawn options.
This helps abstract away the PATH selection so builders dont need to worry about it.
This is no longer needed and nothing will be using in my next PR to update Builders.
Related to #273
=> [now-build-utils] Enhance node version selection

packages/now-next/src/index.ts, packages/now-node-server/index.js, packages/now-node/src/index.ts, packages/now-static-build/index.js
This PR adds support for Node 10 to the remaining builders by parsing `engines` in `package.json`.
- `@now/next`
- `@now/node`
- `@now/node-server`
- `@now/static-build`
Related to #648
Closes #273
=> Add support for node 10 in all builders

packages/now-build-utils/src/fs/run-user-scripts.ts, packages/now-build-utils/src/index.ts
This was added in canary and no stable builders actually use it yet.
I deprecated `enginesMatch` in #648 and then stopped using this method completely in #649 so it should be safe to remove.
The only time it would fail is if someone pinned to this specific canary version: `@now/node@0.5.6-canary.7` (but that is unlikely).
Related to #273
=> [now-build-utils] Remove `enginesMatch` export

README.md
Updates the readme to clarify that the publisher should check the diff to ensure nothing was missed.
=> Add `git diff` to publishing steps in readme

packages/now-build-utils/src/fs/node-version.ts, packages/now-build-utils/test/test.js
As a follow up to @Timer's [comment](https://github.com/zeit/now-builders/pull/648#pullrequestreview-253025302), this PR will ensure we fail fast (build error) when `engines` does not match any supported version or the semver range is completely invalid.
If `engines` is not defined, the default `8.10.x` is used and a log message is printed.
I also changed the tests to be more jest-like.
=> [now-build-utils] Fail if `engines` is invalid

packages/now-python/now_init.py, packages/now-python/test/fixtures/11-asgi/Pipfile, packages/now-python/test/fixtures/11-asgi/Pipfile.lock, packages/now-python/test/fixtures/11-asgi/index.py, packages/now-python/test/fixtures/11-asgi/now.json
ASGI (Asynchronous Server Gateway Interface): https://asgi.readthedocs.io/en/latest/
> ASGI, the emerging Python standard for asynchronous web servers and applications
> -- Django Project
ASGI is supported by Django, [Starlette](https://www.starlette.io/), [Uvicorn](https://www.uvicorn.org/), [Sanic](), [Quart](https://gitlab.com/pgjones/quart/) and more. Many more frameworks (like Werkzeug and Flask) are in the process of adding support too. It would be great to include support for it in the `@now/python` builder.
=> [now-python] Add Python ASGI support

packages/now-node-bridge/src/bridge.ts
To offer better support for https://github.com/zeit/now-builders/pull/657, we can rely on `listen` method that we're using to duck type servers, rather than events on the server instance.
=> [now-node-bridge] Use a callback on server.listen() method rather than server.on('listening')

.github/main.workflow
This reverts commit 5ff2c37147eb203f5199ffe4d4aa9480e3ebaa85.
`release` event is not triggered because we don't create releases when publishing (They appear [here](https://github.com/zeit/now-builders/releases) but this page just displays tags as placeholders for releases).
=> Revert "Only run github action on 'release' event (#662)"

packages/now-next/src/index.ts, packages/now-next/src/utils.ts
This adds handling for the new `[id]` dynamic syntax and removes the old `$id` syntax.
Tested with https://dynamic.jj4.now.sh and `@ijjk/now-next@0.0.1-dev.12`
=> [now-next] Update @now/next for new dynamic syntax

jest.config.js
This PR improves the `git diff` in `jest.config.js`. We can use _Symmetric Difference Notation_ to only look for changes on the PR branch side and not on the `canary` branch side.
See docs for this here : https://git-scm.com/docs/gitrevisions#_dotted_range_notations
=> [tests] Improve git diff in jest config and refactor

packages/now-static-build/src/index.ts, packages/now-static-build/test/fixtures/07-nonzero-sh/build.sh, packages/now-static-build/test/fixtures/07-nonzero-sh/now.json, packages/now-static-build/test/test.js
This improves two error messages:
1. When `now-build` script is missing from `package.json`
2. When neither `.sh` file or `package.json` file is provided as the entrypoint `src`
Fixes #131
=> [now-static-build] Improve msg when missing script

packages/now-static-build/test/fixtures/07-nonzero-sh/build.sh
I forgot to add this to the test in PR #672
Without the random placeholder, the test might appear to pass when it should fail because of de-duping.
=> [now-static-build] Add missing random to test

packages/now-ruby/package.json
Since typescript is only used during development of this builder, it should be `devDependency`.
You can see how large [@now/ruby](https://packagephobia.now.sh/result?p=@now/ruby@0.1.0-canary.4) builder is on Package Phobia (42 MB).
After this change, it will be significantly smaller (under 1 MB).
=> [now-ruby] Move typescript to devDependency

.github/CODEOWNERS
This adds @nathancahill and @coetry, the resident Ruby experts, to codeowners so that we can get more eyes on code reviews.
=> [docs] Add codeowners for ruby

packages/now-bash/index.js, packages/now-build-utils/src/types.ts
Add `import` config prop to `now-bash` but still allows the default imports directly within the `config`.
This also adds the type to `Config` in `now-build-utils`.
=> [now-bash] Add import config prop

packages/now-next/src/index.ts, packages/now-next/test/integration/index.test.js, packages/now-next/test/integration/standard/next.config.js, packages/now-next/test/integration/standard/now.json, packages/now-next/test/integration/standard/pages/goodbye.js
PR #649 broke the Next.js' serverless target feature, causing poor UX/DX for users.
The crux of this problem is that the PR started snapshotting `process.env`, which differs from default behavior. Normally, all `process.env` values are passed down to a child process at creation time.
There was logic in this builder that relied on that non-snapshotting behavior.
---
This PR also removes `__NEXT_BUILDER_EXPERIMENTAL_DEBUG` which is unnecessary since we now leverage Next.js' dev server instead of production builder.
=> [now-next] Reorder process overrides

packages/now-next/src/index.ts, packages/now-node-server/index.js, packages/now-node/src/index.ts
This is a companion to https://github.com/zeit/now-cli/pull/2480.
=> Use the local version of `node` when running via `now dev`

packages/now-bash/package.json, packages/now-build-utils/package.json, packages/now-go/package.json, packages/now-html-minifier/package.json, packages/now-md/package.json, packages/now-mdx-deck/package.json, packages/now-next/package.json, packages/now-node-server/package.json, packages/now-node/package.json, packages/now-optipng/package.json, packages/now-php/package.json, packages/now-python/package.json, packages/now-ruby/package.json, packages/now-rust/package.json, packages/now-static-build/package.json
This PR adds a [homepage](https://docs.npmjs.com/files/package.json#homepage) field to each package.
This allows a user to visit npmjs.com and click "homepage" to go directly to the specified builder's documentation.
Note the "homepage" column  above ^
Closes #40
=> Add homepage to all packages

packages/now-ruby/install-ruby.ts
Release notes for 2.5.5 and 2.5.4:
https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/
https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-5-4-released/
=> [now-ruby] Use ruby 2.5.5

packages/now-ruby/index.ts
Specifies the number of gems Bundler can install in parallel.
https://bundler.io/v2.0/man/bundle-config.1.html
https://bundler.io/v2.0/man/bundle-install.1.html
=> [now-ruby] Use BUNDLE_JOBS=4 for parallel Ruby gem downloads

packages/now-node/src/launcher.ts, packages/now-node/test/fixtures/02-node-server/hapi-async/index.js, packages/now-node/test/fixtures/02-node-server/hapi-async/package.json, packages/now-node/test/fixtures/02-node-server/index.js, packages/now-node/test/fixtures/02-node-server/now.json, packages/now-node/test/fixtures/02-node-server/subdirectory/index.js
Add support for `server.listen()` to `@now/node`.
This will allow us to deprecate `@now/node-server`.
=> [now-node] Add support for `server.listen()`

.github/CODEOWNERS
@lucleray spent a lot of time refactoring the `@now/node` and `@now/node-bridge` packages its good to get eyes when new PRs come in 👀 
Previously there were no owners for `@now/node-bridge` so I added the same owners.
https://github.com/zeit/now-builders/pull/695/files?w=1
=> Add lucleray to codeowners

packages/now-node/build.sh
Fix https://github.com/zeit/now-builders/issues/703.
=> [now-node] Make `types.d.ts` the main types export

packages/now-build-utils/src/fs/run-user-scripts.ts
Some users may wish to use Node 10 from a build script like `build.sh`.
I will do a follow up PR to pass the spawn options from `@now/static-build`.
Related to [this spectrum issue](https://spectrum.chat/zeit/now/is-it-possible-to-specify-the-npm-version~ce099974-91f9-4af6-aec0-72a276fc740d)
Update: I also removed dead code
=> [now-build-utils] Add shell script args / opts

packages/now-next/package.json, packages/now-node/package.json, packages/now-php/package.json, packages/now-wordpress/package.json
When doing `git diff` between `master` and `canary`, only the `version` of the packages should differ, nothing else.
=> Fix branch inconsistencies

packages/now-node-server/package.json
This completes my cleanup and makes `git diff` only show the version as the difference between canary and master.
=> Complete cleanup

packages/now-build-utils/src/detect-builder.ts, packages/now-build-utils/src/detect-routes.ts, packages/now-build-utils/test/test.js
Ignore files and folders with a dot or underscore prefix for api.
=> [now-build-utils] Ignore dot and underscore prefix for api directory

packages/now-bash/index.js, packages/now-go/index.ts, packages/now-python/src/index.ts
Support `zeroConfig` property and increase `maxLambdaSize` for `@now/bash` since the default wasn't enough while testing
=> [now-bash][now-go][now-python] Support zero config

packages/now-node/src/index.ts, packages/now-node/src/typescript.ts, packages/now-node/test/fixtures/18-nested-tsconfig/functions/double-redirect.ts, packages/now-node/test/fixtures/18-nested-tsconfig/functions/package.json, packages/now-node/test/fixtures/18-nested-tsconfig/functions/referer-redirect.ts, packages/now-node/test/fixtures/18-nested-tsconfig/functions/trailing-redirect.ts, packages/now-node/test/fixtures/18-nested-tsconfig/functions/tsconfig.json, packages/now-node/test/fixtures/18-nested-tsconfig/index.ts, packages/now-node/test/fixtures/18-nested-tsconfig/now.json, packages/now-node/test/fixtures/18-nested-tsconfig/package.json, packages/now-node/test/fixtures/18-nested-tsconfig/tsconfig.json
This implements nested tsconfig.json lookup loading by checking for the `tsconfig.json` for each compiled `.ts` file.
We then store a map of builds for each `tsconfig.json` path effectively turning the loader into a builder of builders, while retaining caching within each build itself.
Fixes #724.
=> Nested tsconfig.json lookup support

packages/now-node/src/index.ts, packages/now-node/test/fixtures/25-aws-api/callback/index.js, packages/now-node/test/fixtures/25-aws-api/index.js, packages/now-node/test/fixtures/25-aws-api/now.json, packages/now-node/test/fixtures/25-aws-api/package.json
The idea here is that users should be able to deploy existing AWS Lambda functions to ZEIT Now without modifications besides adding `now.json`.
```json
{
"version": 2,
"builds": [
{
"src": "index.js",
"use": "@now/node",
"config": { "awsLambdaHandler": "index.handler" }
}
]
}
```
This will work with any filename and any function name since the handler is defined in the `config.awsLambdaHandler`.
However multiple entry points will need to use define multiple `builds` instead of using `src` glob syntax.
=> [now-node] Add support for AWS Lambda API usage

packages/now-node/package.json, yarn.lock
This adds https://github.com/zeit/node-file-trace/pull/9 to `node-file-trace`.
=> [now-node] Update node-file-trace to 0.1.6

packages/now-next/src/index.ts
This can cause dynamic routes to not match in production.
Tested at https://dynamic-routing.jj4.now.sh with `@ijjk/now-next@0.0.1-dev.18`
=> Remove extra pre-fixing for dynamic routes

packages/now-build-utils/src/fs/run-user-scripts.ts
Remove mutex because it is not reentrant and hangs on sub-invocation
=> Remove --mutex from yarn command

packages/now-node-bridge/src/bridge.ts
Reverts #766 until we can decide on a configuration for this setting.
"we need to have a discussion on how we plan to expose function setting overriding"
=> Revert "[now-node-bridge] Increase timeout to 10 minutes"

packages/now-static-build/src/index.ts
We want to remove the `defaultRoutes` from the `framework` in `now dev` when a `dev` script was invoked, since the routes won't apply to the custom server of e.g. `gatsby develop`.
=> [now-static-build] Remove default routes for now dev

packages/now-build-utils/src/detect-builder.ts, packages/now-build-utils/test/test.js
Ignore more default routes and builds if they do not that match any builder.
=> [now-build-utils] Ignore more default routes and builds

packages/now-build-utils/src/detect-builder.ts, packages/now-build-utils/src/detect-routes.ts, packages/now-build-utils/test/test.js
Fix file order to make sure the routes and builds are always in the same order.
=> [now-build-utils] Fix file order

.circleci/publish.sh
This has caused too many problems.
Let's ignore any changes to yarn.lock so we can continue to publish.
=> Ignore yarn.lock changes on publish

packages/now-build-utils/src/detect-builders.ts
Display a link with the `build` script warning to explain the warning in more detail.
=> [now-build-utils] Display link for missing `build` script warning

packages/now-next/src/utils.ts, packages/now-next/test/unit/build.test.js
Fixes [now-cli#2385](https://github.com/zeit/now-cli/issues/2385), [next.js#8017](https://github.com/zeit/next.js/issues/8017) and #722
=> Normalize slash for nested paths

packages/now-static-build/src/index.ts
Use `dev` command in zero config when there is no
=> [now-static-build] Use `dev` command in zero config when there is no command

packages/now-node/src/index.ts
Fixes a regression from #765 that was causing 405 Method Not Allowed in some express apps.
The reason why our tests don't catch this is due to a different bug regarding symlink creation (or more likely, symlink upload).
=> [now-node] Fix symlink regression

packages/now-build-utils/src/detect-builders.ts, packages/now-build-utils/test/test.js
We don't want to use canary builders for zero config.
Fixes #816
=> [now-build-utils] Do not use `canary` for zero config

package.json, packages/now-build-utils/build.sh, packages/now-build-utils/package.json, packages/now-build-utils/test/test.js
Related to #471
This runs ncc on `@now/build-utils` before publishing to npm which reduces install time for production builds.
I also changed the build-utils test suite to run tests fixtures for `@now/next`, `@now/node`, and `@now/static-build`.
=> [now-build-utils] Use ncc before publishing to npm

packages/now-next/src/index.ts
The right status in case a page is not found.
=> [now-next] Update _error.js route to return 404 status instead of 200

packages/now-node/test/fixtures/18-nested-tsconfig/functions/double-redirect.ts, packages/now-node/test/fixtures/18-nested-tsconfig/now.json
Since `now-proxy` changed, these tests started failing with
```
Error: Fetched page https://test-lauxkjuiu.now.sh// does not contain trailing-redirect:3ed9f90b3ed9f90b3ed9f9. Instead it contains root:3ed9f90b3ed9f90b3ed9f9
```
This fixes the tests so we are checking the correct thing.
=> [now-node] Fix `18-nested-tsconfig` tests

packages/now-next/.gitignore, packages/now-next/build.sh, packages/now-next/getBridgeTypes.sh, packages/now-next/package.json, packages/now-next/src/index.ts, packages/now-next/src/launcher.ts, packages/now-next/test/unit/utils.test.js, test/lib/deployment/now-deploy.js, yarn.lock
Related to #471
The changes:
- Copy `bridge.ts` source code, not just types (necessary to satisfy ncc)
- Remove dependency on `@now/node-bridge` (because previous step covers that)
- Move `dependencies` to `devDependencies` and pin them
- Change `prepublish` to `prepublishOnly` to avoid running during `yarn install`
- Run ncc on builder source code
=> [now-next] Use ncc before publishing to npm

packages/now-next/build.sh, packages/now-next/test/unit/export.test.js
Fixes #845
Since `index.js` uses `child_process.fork()` to start the `dev-server.js` file, the dev server also needs to be its own bundle.
This regression was introduced in #832
=> [now-next] Fix dev-server bundle output

packages/now-build-utils/fs/download.js, packages/now-build-utils/fs/get-writable-directory.js, packages/now-build-utils/fs/glob.js, packages/now-build-utils/fs/rename.js, packages/now-build-utils/fs/run-user-scripts.js, packages/now-build-utils/fs/stream-to-buffer.js, packages/now-build-utils/test/test.js
This fixes a regression from #820 affecting `@now/lambda` and other legacy builders that expect to be able to require a specific path.
=> [now-build-utils] Fix require file path for legacy builders

packages/now-node/package.json, yarn.lock
Bumps `node-file-trace` to version [0.2.4](https://github.com/zeit/node-file-trace/releases/tag/0.2.4).
Related to #848
=> [now-node] Bump node-file-trace to 0.2.4

packages/now-build-utils/src/detect-builders.ts, packages/now-build-utils/test/test.js
We want to be able to set the version tag (`canary` or `latest`) for zero-config.
This further removes builders that we don't want to include for zero-config by default.
=> [now-static-build] Allow setting the `tag` for zero-config builders

packages/now-build-utils/src/detect-builders.ts, packages/now-build-utils/test/test.js
Remove `@now/nuxt` from zero-config default builders
=> [now-build-utils] Remove `@now/nuxt` from default builders

packages/now-node/package.json, yarn.lock
This PR bumps `@zeit/node-file-trace` to version [0.2.5](https://github.com/zeit/node-file-trace/releases/tag/0.2.5)
Fixes #851
=> [now-node] Bump node-file-trace to 0.2.5

packages/now-python/src/index.ts
This fixes #841 where an upstream dependency broke converting a `Pipfile.lock` into `requirements.txt` with lines like this 
```
sentry-sdk = {extras = ["flask"],version = "*"}
```
We now switched to a seemingly more robust implementation which is based upon https://github.com/sarugaku/requirementslib and can handle `extras` correctly.
Replaces https://github.com/zeit/now-builders/pull/856
=> [now-python] Use pipfile2req to convert pipfile to requirements.txt

packages/now-node/package.json, yarn.lock
Bumps `@zeit/node-file-trace` to version [0.2.6](https://github.com/zeit/node-file-trace/releases/tag/0.2.6)
Fixes #855
=> [now-node] Bump node-file-trace to 0.2.6

packages/now-build-utils/src/fs/run-user-scripts.ts, packages/now-static-build/src/index.ts
This makes sure that `process.env` will be a reference and it will manually add `node_modules/.bin` to the PATH env, since it won't work on windows otherwise.
I'm not yet sure on why this is required, since this works just fine:
```
require('cross-spawn')('yarn', ['--cwd', process.cwd(), 'run', 'build'], { 'stdio': 'inherit', env: { ...process.env }, cwd: process.cwd() })
```
this should be the exact same thing the builder is doing
=> [now-build-utils][now-static-build] Fix spawn options for windows

packages/now-build-utils/src/detect-routes.ts, packages/now-build-utils/test/test.js
Disable directory listing for api routes.
`/api/index.js`, `/api/[endpoint].js` continue to work.
=> [now-build-utils] Disable directory listing for api routes

packages/now-build-utils/src/detect-routes.ts, packages/now-build-utils/test/test.js
This allows us to disable the directory listing but still support all routes that could be used.
For example, `index`, `index.js` or no name at all, since it is index.
Fixes #881
=> [now-build-utils] Fix 404 for index routes

packages/now-build-utils/src/detect-builders.ts, packages/now-build-utils/test/test.js
We know that `.d.ts` files are never going to be lambdas so this PR will exclude them.
The reason is that `.d.ts` is a type declaration, it does not contain runtime code.
=> [now-build-utils] Fix TS globbing for zero config

DEVELOPING_A_BUILDER.md, README.md
This pull request adds the Builder's Developer Reference to this repository instead of the docs, as a resource to link to, and to avoid adding noise to the docs that doesn't need to be there for users to bump into.
=> [docs] Add Builders Developer Reference

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
Bump `@zeit/node-file-trace` to [0.2.7](https://github.com/zeit/node-file-trace/releases/tag/0.2.7) with support for Windows.
Related to #869
=> [now-node][now-next] Bump node-file-trace to 0.2.7

packages/now-node/src/index.ts
Fixes #869 
This was a strange bug to track down and this does not address the root cause which likely needs to be fixed in `now-cli`.
When running `now dev` on Windows, the `build({ workPath, entrypoint })` function is invoked with inconsistent path separators. For example:
- entrypoint: `zeit/api/api-handler.ts`
- workPath: `C:\Users\styfle\Code\zeit-now-ts-debugging`
Most of the time this isn't a problem, but in one case, there was a strict string comparison that was failing so I used `path.resolve()` to convert both to absolute paths before comparing.
=> [now-node] Fix windows typescript entrypoint bug

packages/now-build-utils/src/lambda.ts
This disables compression of the `.zip` for lambdas, making it more like `.tar`. This should help speed up builds. 😄
=> Disable compression for Zips

packages/now-next/src/create-serverless-config.ts
Next.js users should not be automatically opted into an experimental feature unless they're explicitly on a Next.js canary version.
=> [@now/next] Serverless Trace target for Next.js canary only

packages/now-build-utils/src/lambda.ts
Reverts zeit/now-builders#901
This did not have a meaningful effect on the end-speed, it shaved about ~300ms of a 4s `createLambda` operation. It amounted to about 20s savings for `front`.
This is still "significant", but the whole operation still took 3.66 minutes instead of 4 minutes. 😄 
---
I do not feel strongly about keeping or reverting this, so I'll leave it to the PR reviewer to close this PR or revert the change!
=> Revert "Disable compression for Zips"

packages/now-build-utils/src/detect-routes.ts, packages/now-build-utils/test/fixtures/01-zero-config-api/.gitignore, packages/now-build-utils/test/fixtures/01-zero-config-api/api/[endpoint].js, packages/now-build-utils/test/fixtures/01-zero-config-api/api/[endpoint]/[id].js, packages/now-build-utils/test/fixtures/01-zero-config-api/package.json, packages/now-build-utils/test/fixtures/02-zero-config-api/.gitignore, packages/now-build-utils/test/fixtures/02-zero-config-api/api/date.js, packages/now-build-utils/test/fixtures/02-zero-config-api/api/date/index.js, packages/now-build-utils/test/fixtures/02-zero-config-api/api/index.js, packages/now-build-utils/test/fixtures/02-zero-config-api/package.json, packages/now-build-utils/test/test.js, test/lib/deployment/test-deployment.js
Fix 404 trailing slash for index files and add tests.
This makes sure that routes like `/api/date` return a 200 instead of a 404 when the source is `/api/date/index.js`.
It further updates the unit tests and adds integration tests to test those cases.
=> [now-build-utils] Fix 404 trailing slash for index files and add tests

packages/now-go/index.ts
This PR update link to docs when `analyzer` couldn't parse the `entrypoint`.
=> [now-go] Update link to docs

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
Bump `@zeit/node-file-trace` to version [0.2.8](https://github.com/zeit/node-file-trace/releases/tag/0.2.8).
Fixes #903
=> [now-node][now-next] Bump node-file-trace to 0.2.8

PUBLISHING.md, README.md, VERSIONING.md
Moving versioning section from docs to the builder repo https://github.com/zeit/docs/pull/871
=> [docs] Add versioning documentation

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
Bumps `@zeit/node-file-trace` to version [0.2.9](https://github.com/zeit/node-file-trace/releases/tag/0.2.9) with a fix for `tsx` input files.
Related to #869 cc @tylerc
=> [now-node][now-next] Bump node-file-trace to 0.2.9

packages/now-next/src/index.ts
Apparently `path.join` cannot prepend `./`, meaning:
```js
> path.join('./', 'foo') === 'foo'
true
```
This require **must** be relative -- it's not absolute. 
I have no clue how our integration tests were passing before this change, so we should probably figure out a test for this.
=> [now-next] Join bundle require path manually

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
Bumps `@zeit/node-file-trace` to version [0.2.10](https://github.com/zeit/node-file-trace/releases/tag/0.2.10) with a fix for phantom
Related to https://github.com/zeit/node-file-trace/pull/46
=> Bump node-file-trace to 0.2.10

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
This adds support for webpack-emitted source code, specifically for use in Next.js.
=> Upgrade `@zeit/node-file-trace` to `0.2.11`

packages/now-static-build/src/index.ts
Closes https://github.com/srilq/euanmarten/issues/1.
Now dev builder expects object return type:
https://github.com/zeit/now-cli/blob/c5ef4b1dc585b7cb6bfd74135edb593961bd9d00/src/util/dev/builder.ts#L272
Using `.sh` build scripts with `now dev` currently results in the following error:
```
now dev --debug
> [debug] [2019-08-17T17:26:24.485Z] Found config in file /Users/sril/src/euanmarten/now.json
> [debug] [2019-08-17T17:26:24.501Z] Using Now CLI 16.1.1
> [debug] [2019-08-17T17:26:24.525Z] user supplied known subcommand
> Now CLI 16.1.1 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-08-17T17:26:24.672Z] The yarn executable is already cached, not re-downloading
> [debug] [2019-08-17T17:26:24.675Z] Reading `package.json` file
> [debug] [2019-08-17T17:26:24.675Z] Reading …
```
=> [now-static-build] Fix "TypeError: Cannot convert undefined or null to object"

packages/now-next/src/create-serverless-config.ts
We've shipped this change to ZEIT.co so we feel confident in its ability to be the default.
Note for readers: this change is transparently applied by the Next.js builder to achieve faster and more accurate build results, akin to `next dev` behavior. 
You can continue to use `target: 'serverless'` during `next dev` until we make this the default in a future release of Next.js.
=> [now-next] Always use node-file-trace if available

packages/now-next/package.json, packages/now-node/package.json, yarn.lock
Bump `@zeit/node-file-trace` to [0.2.13](https://github.com/zeit/node-file-trace/releases/tag/0.2.13) with a special case for [argon2](https://github.com/zeit/node-file-trace/pull/53).
Fixes #929
=> [now-node][now-next] Bump node-file-trace to 0.2.13
